config/routes.rb
SeedCms::Engine.routes.draw do
  scope "/:content_class" do
    resources :entries
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/seed_cms/application_record.rb
module SeedCms
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/seed_cms/concerns/searchable.rb
module SeedCms
  module Concerns
    module Searchable
      extend ActiveSupport::Concern

      included do
        has_many :search_data, class_name: 'SeedCms::EntrySearchData'
        after_save :update_search_index
      end

      module ClassMethods
        def searchable_attributes(*args)
          @searchable_attributes = args if args.any?
          @searchable_attributes ||= []
        end

        def search(query)
          select('DISTINCT ON (entry_id) entry_id, seed_cms_entries.*').
            joins(:search_data).
            where("search_data @@ plainto_tsquery('english', :q)", q: query).
            order("entry_id, ts_rank(search_data, plainto_tsquery('%s')) desc" % send(:sanitize_sql, query))
        end
      end

      def search_attributes
        self.class.searchable_attributes.each_with_object({}) do |attr_name, search_data|
          search_data[attr_name] = send(attr_name)
        end
      end

      def update_search_index
        SeedCms::EntrySearchData.index_entry_data(id, search_attributes)
      end
    end
  end
end

app/models/seed_cms/entry.rb
module SeedCms
  class Entry < ApplicationRecord
    include SeedCms::Concerns::Searchable
    
    scope :published, -> { where('published_at <= ?', Time.zone.now) }

    before_save :set_slug

    def self.content_attr(attr_name, attr_type = :string)
      content_attributes[attr_name] = attr_type

      define_method(attr_name) do
        self.payload ||= {}
        self.payload[attr_name.to_s]
      end

      define_method("#{attr_name}=".to_sym) do |value|
        self.payload ||= {}
        self.payload[attr_name.to_s] = value
      end
    end

    def self.content_attributes
      @content_attributes ||= {}
    end

    def set_slug
      if self.slug.blank?
        self.slug = self.title.downcase.gsub( /[^A-Za-z]/, "_" )
      end
    end
  end
end

app/models/seed_cms/entry_search_data.rb
module SeedCms
  class EntrySearchData < ApplicationRecord
    belongs_to :entry

    validates :entry_id, presence: true
    validates :attr_name, presence: true, uniqueness: { scope: :entry_id }

    def self.index_entry_data(entry_id, search_attributes)
      search_attributes.each do |attr_name, value|
        find_or_create_by(entry_id: entry_id, attr_name: attr_name)

        where(entry_id: entry_id, attr_name: attr_name).update_all([
          "search_data = to_tsvector('english', :search_data)",
          search_data: value
        ])
      end
    end
  end
end

app/controllers/seed_cms/application_controller.rb
module SeedCms
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def content_entry_path( entry )
      if entry && entry.id
        entry_path( content_class: content_class.tableize, id: entry.id)
      else
        entries_path( content_class: content_class.tableize )
      end
    end
    helper_method :content_entry_path

    def edit_content_entry_path( entry )
      edit_entry_path( content_class: content_class.tableize, id: entry.id)
    end
    helper_method :edit_content_entry_path

    def content_entries_path
      entries_path(content_class: content_class.tableize)
    end
    helper_method :content_entries_path
  end
end

app/controllers/seed_cms/entries_controller.rb
require_dependency "seed_cms/application_controller"

module SeedCms
  class EntriesController < ApplicationController
    before_action :set_entry, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :check_access

    def index
      @entries = Entry.where(type: content_class)
    end

    def show
      render :edit
    end

    def new
      @entry = Entry.new(type: content_class)
    end

    def edit
    end

    def create
      @entry = Entry.new(entry_params)
      if @entry.save
        redirect_to content_entries_path, notice: 'Entry was successfully created.'
      else
        render :new
      end
    end

    def update
      if @entry.update(entry_params)
        redirect_to content_entries_path, notice: 'Entry was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @entry.destroy
      redirect_to content_entries_path, notice: 'Entry was successfully destroyed.'
    end

    private

    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      allowed_attrs = %i(id type title slug published_at)
        .concat(content_class.constantize.content_attributes.keys)

      params.require(:entry).permit(*allowed_attrs)
    end

    def content_class
      @content_class ||= params[:content_class].classify
    end
    helper_method :content_class

    def check_access
      case action_name
      when 'index'
        unless can? :read, content_class
          redirect_to '/', flash: { error: "You can't read content" }
        end
      when 'new', 'create'
        unless can? :create, content_class
          redirect_to '/', flash: { error: "You can't create content" }
        end
      when 'show'
        unless can? :read, @entry
          redirect_to '/', flash: { error: "You can't read content" }
        end        
      when 'edit', 'update'          
        unless can? :update, @entry
          redirect_to '/', flash: { error: "You can't update content" }
        end
      when 'destroy'
        unless can? :destroy, @entry
          redirect_to '/', flash: { error: "You can't destroy content" }
        end
      else
        throw "Unknown action #{action_name}"
      end
    end
  end
end

app/helpers/seed_cms/application_helper.rb
module SeedCms
  module ApplicationHelper
  end
end

app/helpers/seed_cms/entries_helper.rb
module SeedCms
  module EntriesHelper
  end
end

app/views/layouts/seed_cms/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seed cms</title>
  <%= stylesheet_link_tag    "seed_cms/application", media: "all" %>
  <%= javascript_include_tag "seed_cms/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if !flash.empty? %>
    <% flash.keys.each do |k| %> 
        <div class="alert alert-info <%= k %>">
            <%= flash[k] %>
        </div>  
    <% end %>   
  <% end %>
  <div class="container-fuild">
    <div class="row">
      <div class="content">
        <%= yield %>
      </div>
      <div class="sidebar">
        <ul class="nav nav-pulls nav-stacked">
          <% SeedCms.configuration.content_classes.each do |class_name| %>
            <li>
              <%= link_to class_name.tableize.titleize, entries_path(content_class: class_name.tableize) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</body>
</html>

app/views/seed_cms/entries/_form.html.erb
<%= simple_form_for(@entry, as: :entry, url: content_entry_path( @entry )) do |f| %>
    <%= f.hidden_field :type, value: @entry.type %>

    <%= f.input :title %>

    <% @entry.class.content_attributes.each do |attr_name, attr_type| 
      if attr_type == :ckeditor %>
        <%= f.input attr_name, as: attr_type, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
      <% else %>
        <%= f.input attr_name, as: attr_type %>
      <% end %>
    <% end %>

    <%= f.input :slug %>
    <%= f.input :author_name %>
    

    <div class="row">
      <div class='col-xs-12'>
        <label class="string optional control-label" for="datetimepicker4">Published At</label>

          <input type='text' class="form-control" id='datetimepicker4' name="entry[published_at]"/>
      </div>
      <script type="text/javascript">
          $(function () {
              $('#datetimepicker4').datetimepicker({
                format: "MMM D, YYYY H:m",
                defaultDate: '<%= (@entry.published_at || Time.now).strftime( "%m/%d/%y %H:%M") %>'
              });
          });
      </script>
    </div>

    <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/seed_cms/entries/edit.html.erb
<%= render "form" %>

app/views/seed_cms/entries/index.html.erb
<h1><%= content_class.tableize.titleize %></h1>

<%= link_to "New #{content_class.titleize}", new_entry_path, class: 'btn btn-primary space-2' %>

<table class="table space-4">
  <thead>
    <tr>
      <th>Title</th>
      <th>Created at</th>
      <th>Published at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= link_to entry.title, content_entry_path(entry) %></td>
        <td><%= time_ago_in_words entry.created_at %> ago</td>
        <td><%= entry.published_at.strftime "%m/%d/%y %H:%M" %></td>
        <td><%= link_to 'Edit', edit_content_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', content_entry_path(entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/seed_cms/entries/new.html.erb
<%= render "form" %>